services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH"
      /opt/render/project/poetry/bin/poetry install
    startCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH"
      /opt/render/project/poetry/bin/poetry run uvicorn main:app --host 0.0.0.0 --port $PORT