services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH"
      poetry install

    startCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH"
      poetry run uvicorn main:app --host 0.0.0.0 --port $PORT